version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - elk
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
     - '15672'
     - '5672'

  rest-client-service:
    image: displayitregistryqa.azurecr.io/limestonedigital-client-displayit/rest-client-service
    domainname: displayit-app-test
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'ASPNETCORE_URLS=http://+:7071'
      - 'ConnectionStrings__RabbitMqConnectionString=rabbitmq://guest:guest@localhost:5672'
    build:
        context: .
        dockerfile: ./RestClient/Dockerfile
    networks:
      - elk
    ports:
      - '7071:7071'
    expose:
      - '7071'
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

networks:
  elk:
    driver: bridge